version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - 
    id: "windows_i686"
    env:
      - CGO_ENABLED=1
      - CXX=i686-w64-mingw32-g++ 
      - CC=i686-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - 386
  - 
    id: "windows_64"
    env:
      - CGO_ENABLED=1
      - CXX=x86_64-w64-mingw32-g++ 
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
  - 
    id: "linux"
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "windows" }}Windows
      {{- else if eq .Os "linux" }}Linux
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats:
          - zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  prerelease: auto